INSERT INTO runners (name, gender, country, birth, team, info) VALUES
('Adrien Briffod','Homme','France',NULL,NULL,NULL),
('Anders Kjaerevik','Homme','Norway',NULL,NULL,NULL),
('Andreu Blanes','Homme','Spain',NULL,NULL,NULL),
('Andy Wacker','Homme','USA',NULL,NULL,NULL),
('Antonio Martinez Perez','Homme','Spain',NULL,NULL,NULL),
('Bogdan Damian','Homme','Poland',NULL,NULL,NULL),
('Cameron Smith','Homme','USA',NULL,NULL,NULL),
('Cesare Maestri','Homme','Italy',NULL,NULL,NULL),
('Christian Allen','Homme','USA',NULL,NULL,NULL),
('Daniel Pattis','Homme','Italy',NULL,NULL,NULL),
('Dominik Rolli','Homme','Switzerland',NULL,NULL,NULL),
('Eder Belmont','Homme','Spain',NULL,NULL,NULL),
('Elhousine Elazzaoui','Homme','Morocco','1992-03-16','Salomon / supported by Kilian Jornet (associated)','Moroccan trail standout'),
('Ephantus Mwangi Njeri','Homme','Kenya',NULL,NULL,NULL),
('Francesco Puppi','Homme','Italy',NULL,NULL,NULL),
('Jan Torella Oller','Homme','Norway',NULL,NULL,NULL),
('Joey Hadorn','Homme','Switzerland','1997-04-11','Salomon Swiss Team','Strong mountain/trail racer'),
('Jonas Soldini','Homme','Italy',NULL,NULL,NULL),
('Juan Belman','Homme','Spain',NULL,NULL,NULL),
('Juan Carlos Carera','Homme','Spain',NULL,NULL,NULL),
('Juho Ylinen','Homme','Finland',NULL,NULL,NULL),
('Luca del Pero','Homme','Italy',NULL,NULL,NULL),
('Lukas Ehrle','Homme','Germany',NULL,NULL,NULL),
('Lorenzo Beltrami','Homme','Italy',NULL,NULL,NULL),
('Martin Nilsson','Homme','Sweden',NULL,NULL,NULL),
('Marcin Kubica','Homme','Poland',NULL,NULL,NULL),
('Mason Coppi','Homme','Italy',NULL,NULL,NULL),
('Miguel Ángel Pérez Alvarado','Homme','Spain',NULL,NULL,NULL),
('Nashon Kiplimo','Homme','Kenya',NULL,NULL,NULL),
('Nicholas Turco','Homme','USA',NULL,NULL,NULL),
('Samwel Kiprotich','Homme','Kenya',NULL,NULL,NULL),
('Patrick Kipngeno','Homme','Kenya','1993-06-18','Run2gether / On (sponsor)','Multiple Golden Trail podiums'),
('Paul Machoka','Homme','Kenya',NULL,NULL,NULL),
('Philemon Kiriago','Homme','Kenya',NULL,NULL,NULL),
('Pierre Galbourdin','Homme','France',NULL,NULL,NULL),
('Remi Leroux','Homme','France',NULL,NULL,NULL),
('Richard Atuya','Homme','Kenya',NULL,NULL,NULL),
('Roberto Delorenzi','Homme','Italy',NULL,NULL,NULL),
('Ruy Ueda','Homme','Japan',NULL,NULL,NULL),
('Ryunosuke Omi','Homme','Japan',NULL,NULL,NULL),
('Stian Angermund','Homme','Norway',NULL,NULL,NULL),
('Taylor Stack','Homme','USA',NULL,NULL,NULL),
('Theo Bourgeois','Homme','France',NULL,NULL,NULL),
('Thomas Cardin','Homme','France',NULL,NULL,NULL),
('Thomas Roach','Homme','Australia',NULL,NULL,NULL),
('Timothy Kibett','Homme','Kenya',NULL,NULL,NULL),
('Ezekiel Rutto','Homme','Kenya',NULL,NULL,NULL),
('Alexa Aragon','Femme','USA',NULL,NULL,NULL),
('Alice Gaggi','Femme','Italy',NULL,NULL,NULL),
('Allie McLaughlin','Femme','USA',NULL,NULL,NULL),
('Andrine Benjaminsen','Femme','Norway',NULL,NULL,NULL),
('Anna Gibson','Femme','UK',NULL,NULL,NULL),
('Betty Bergstrand','Femme','Sweden',NULL,NULL,NULL),
('Carmen Trinidad Ramiro','Femme','Spain',NULL,NULL,NULL),
('Caroline Kimutai','Femme','Kenya',NULL,NULL,NULL),
('Céline Aebi','Femme','Switzerland',NULL,NULL,NULL),
('Courtney Coppinger','Femme','Ireland',NULL,NULL,NULL),
('Faith Kiplagat','Femme','Kenya',NULL,NULL,NULL),
('Honoka Akiyama','Femme','Japan',NULL,NULL,NULL),
('Ida Amelie Robsahm','Femme','Norway',NULL,NULL,NULL),
('Ikram Rharsalla','Femme','Morocco',NULL,NULL,NULL),
('Jade Belzberg','Femme','Canada',NULL,NULL,NULL),
('Josefina Pérez Licona','Femme','Mexico',NULL,NULL,NULL),
('Joyce Njeru','Femme','Kenya',NULL,NULL,NULL),
('Joyline Chepngeno','Femme','Kenya',NULL,NULL,NULL),
('Judith Wyder','Femme','Switzerland',NULL,NULL,NULL),
('Katie Schide','Femme','USA',NULL,NULL,NULL),
('Lauren Gregory','Femme','USA',NULL,NULL,NULL),
('Laura Hottenrott','Femme','Germany',NULL,NULL,NULL),
('Lingjie Chi','Femme','China',NULL,NULL,NULL),
('Madalina Florea','Femme','Romania',NULL,NULL,NULL),
('Marie Nivet','Femme','France',NULL,NULL,NULL),
('Marta Martinez Abellan','Femme','Spain',NULL,NULL,NULL),
('Miao Yao','Femme','China',NULL,NULL,NULL),
('Maude Mathys','Femme','Switzerland',NULL,NULL,NULL),
('Malen Osa','Femme','Spain',NULL,NULL,NULL),
('Maria Fuentes','Femme','Spain',NULL,NULL,NULL),
('Miriam Chepkirui','Femme','Kenya',NULL,NULL,NULL),
('Naomi Lang','Femme','USA',NULL,NULL,NULL),
('Oihana Kortazar','Femme','Spain',NULL,NULL,NULL),
('Patricia Pineda Cornejo','Femme','Chile',NULL,NULL,NULL),
('Philiaries Kisang','Femme','Kenya',NULL,NULL,NULL),
('Rachel Tomajczyk','Femme','USA',NULL,NULL,NULL),
('Rosa Lara Feliu','Femme','Spain',NULL,NULL,NULL),
('Sarah Carter','Femme','USA',NULL,NULL,NULL),
('Sara Alonso','Femme','Spain','1999-04-17','ASICS','Winner at Kobe 2025 and Zegama 2025 (Golden Trail results).'),
('Sara Willhoit','Femme','USA',NULL,NULL,NULL),
('Silvia Hernández González','Femme','Spain',NULL,NULL,NULL),
('Silvia Schwaiger','Femme','Austria',NULL,NULL,NULL),
('Susanna Saapunki','Femme','Finland',NULL,NULL,NULL),
('Sydney Petersen','Femme','USA',NULL,NULL,NULL),
('Takako Takamura','Femme','Japan',NULL,NULL,NULL),
('Theres Leboeuf','Femme','Switzerland',NULL,NULL,NULL),
('Valentine Rutto','Femme','Kenya',NULL,NULL,NULL),
('Vivien Bonzi','Femme','France',NULL,NULL,NULL),
('Weronika Matuszczak','Femme','Poland',NULL,NULL,NULL),
('Yoshimi Tanaka','Femme','Japan',NULL,NULL,NULL);
